---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Rocky)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ( ansible_distribution | lower ) == "rocky"

  - name: install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ( ansible_distribution | lower ) == "debian"


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Debian servers
    tags: apache, apache2, debian
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
      state: present
    when: ( ansible_distribution | lower) == "debian"

  - name: Install apache and php for Rocky servers
    tags: apache, rocky, httpd
    ansible.builtin.dnf:
      name:
        - httpd
        - php
      state: present
    when: ( ansible_distribution | lower) == "rocky"


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb for Debian servers
    tags: debian, db, mariadb
    ansible.builtin.apt:
      name:
        - mariadb-server
      state: present
    when: ( ansible_distribution | lower) == "debian"

  - name: Install mariadb for Rocky servers
    tags: rocky, db, mariadb
    ansible.builtin.dnf:
      name:
        - mariadb
      state: present
    when: ( ansible_distribution | lower) == "rocky"


- hosts: file_servers
  become: true
  tasks:

  - name: Install samba for file servers
    tags: samba
    ansible.builtin.package:
      name:
        - samba
      state: present