---

- hosts: all
  become: true
  tasks:

  - name: Load OS-specific package variables
    ansible.builtin.include_vars:
      file: "vars/{{ ansible_distribution | lower }}.yml"

  - name: Remove apache/php packages
    ansible.builtin.package:
      name:
        - "{{ pkg_apache }}"
        - "{{ pkg_php }}"
        - "{{ pkg_mariadb }}"
        - "{{ pkg_samba }}"
      state: absent
      update_cache: yes
